### ISSUE TITLE
Error with clothing mod

### ISSUE THREAD

**Issue by hunterdelyx1** [vegasd/minetest-mods#45]
19:06:43: ERROR[main]: ServerError: ...e/xunto/.minetest/worlds/123/worldmods/clothing/init.lua:6: bad argument #1 to 'ipairs' (table expected, got nil)
19:06:43: ERROR[main]: stack traceback:
19:06:43: ERROR[main]: 	[C]: in function 'ipairs'
19:06:43: ERROR[main]: 	...e/xunto/.minetest/worlds/123/worldmods/clothing/init.lua:6: in function 'update_skin'
19:06:43: ERROR[main]: 	...e/xunto/.minetest/worlds/123/worldmods/clothing/init.lua:21: in function <...e/xunto/.minetest/worlds/123/worldmods/clothing/init.lua:20>
19:06:43: ERROR[main]: 	/usr/share/minetest/builtin/game/register.lua:348: in function </usr/share/minetest/builtin/game/register.lua:336>

**Comment by sullome** [comment]
@hunterdelyx1, проверь мод ещё раз. Не наблюдаю подобной ошибки сейчас.

**Comment by sullome** [comment]
Хотя нет, понял в чём проблема. Дело в том что список, в котором хранится одежда, создаётся в register_on_newplayer. Таким образом, все игроки, которые в мире уже присутствуют на момент подключения мода, остаются без этого списка.
Пропишу небольшой фикс этого. Проблема не должна появляться в новосозданных мирах.

**Comment by sullome** [comment]
Fixed: c93dee8cec8ddd24a105a1d96fc836ce016ab741
